const content = [
  {
    id: 1,
    name: 'Mary Lou Adame Martinez',
    body: 'This is a placeholer for the time being. Here the individual can talk a little bit about themselves and anything else they would like to add inclduing hobbies, interests, or places they like.',
    image: 'MaryLou.jpg',
    licnum: 'DRE Lic. #1234567',
    phone: '+1 (949)123-4567',
    email: 'teammarylou@caza.gmail',
  },
  {
    id: 2,
    name: 'Evan Martinez',
    body: 'This is a placeholer for the time being. Here the individual can talk a little bit about themselves and anything else they would like to add inclduing hobbies, interests, or places they like.',
    image: 'Evan.JPG',
    licnum: 'DRE Lic. #1234567',
    phone: '+1 (949)123-4567',
    email: 'teammarylou@caza.gmail',
  },
  {
    id: 3,
    name: 'Jasper Freedman',
    body: 'This is a placeholer for the time being. Here the individual can talk a little bit about themselves and anything else they would like to add inclduing hobbies, interests, or places they like.',
    image: '',
    licnum: 'DRE Lic. #1234567',
    phone: '+1 (949)123-4567',
    email: 'teammarylou@caza.gmail',
  },
  {
    id: 4,
    name: 'Isaac Koczwara',
    body: 'This is a placeholer for the time being. Here the individual can talk a little bit about themselves and anything else they would like to add inclduing hobbies, interests, or places they like.',
    image: 'Isaac.JPG',
    licnum: 'DRE Lic. #1234567',
    phone: '+1 (949)123-4567',
    email: 'teammarylou@caza.gmail',
  },
  {
    id: 5,
    name: 'Katherine Brough',
    body: 'This is a placeholer for the time being. Here the individual can talk a little bit about themselves and anything else they would like to add inclduing hobbies, interests, or places they like.',
    image: '',
    licnum: 'DRE Lic. #1234567',
    phone: '+1 (949)123-4567',
    email: 'teammarylou@caza.gmail',
  },
  {
    id: 6,
    name: 'Zack',
    body: 'This is a placeholer for the time being. Here the individual can talk a little bit about themselves and anything else they would like to add inclduing hobbies, interests, or places they like.',
    image: '',
    licnum: 'DRE Lic. #1234567',
    phone: '+1 (949)123-4567',
    email: 'teammarylou@caza.gmail',
  },
  {
    id: 7,
    name: 'Quin Araiza Barron',
    body: 'This is a placeholer for the time being. Here the individual can talk a little bit about themselves and anything else they would like to add inclduing hobbies, interests, or places they like.',
    image: 'Quin.jpg',
    licnum: 'DRE Lic. #1234567',
    phone: '+1 (949)123-4567',
    email: 'teammarylou@caza.gmail',
  },
]

export default content
